packaging:
  add:
    - target/osiam
    - target/addon-self-administration
    - target/dependency/addon-self-administration-plugin-example.jar

links:
  - ${database.container}
  - ldap

ports:
  - 8180
  - 11110
  - 8000

healthChecks:
  pings:
    - url: ${osiam.test.host}/manager/text/list
      timeout: 250000
      pattern: osiam:running

tag: ${project.artifactId}_tomcat-${database.container}
